# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo_list', '0002_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
